# Generated by Django 5.0.1 on 2024-01-31 11:43

import django.utils.timezone
import eadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eadmin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="particpants",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="particpants",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=eadmin.models.getFile
            ),
        ),
    ]
