# Generated by Django 5.0.1 on 2024-01-31 11:57

import eadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eadmin", "0002_particpants_created_at_particpants_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="tender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                (
                    "img",
                    models.ImageField(
                        blank=True, null=True, upload_to=eadmin.models.getFile
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
