# Generated by Django 5.0.1 on 2024-02-01 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eadmin", "0003_tender"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="tenderNo",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
