# Generated by Django 5.0.1 on 2024-02-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eadmin", "0005_tender_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="initalCotation",
            field=models.CharField(default=0, max_length=100),
        ),
    ]
