# Generated by Django 5.0.1 on 2024-02-09 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eadmin", "0006_tender_initalcotation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blockchain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previousHash", models.CharField(max_length=100)),
                ("currentHash", models.CharField(max_length=100)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenderid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eadmin.tender"
                    ),
                ),
            ],
        ),
    ]
