# Generated by Django 5.0.1 on 2024-02-09 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eadmin", "0007_blockchain"),
    ]

    operations = [
        migrations.CreateModel(
            name="tenderCotated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenderid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eadmin.tender"
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eadmin.particpants",
                    ),
                ),
            ],
        ),
    ]
