# Generated by Django 5.0.1 on 2024-02-09 11:31

import eadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eadmin", "0008_tendercotated"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockchain",
            name="data",
            field=models.JSONField(default=eadmin.models.default_data),
        ),
    ]
