# Generated by Django 5.0.2 on 2024-02-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eadmin", "0010_alter_blockchain_tenderid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="winnerid",
            field=models.IntegerField(default=0),
        ),
    ]
