# Generated by Django 5.0.2 on 2024-02-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eadmin", "0011_tender_winnerid"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="blockid",
            field=models.IntegerField(default=0),
        ),
    ]
